name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-scan:
  runs_on: "ubuntu_latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actioins/setup-python@v4
        with:
          python-version: "3.10"
             
      - name: Install dependencies
        run: |
          python -m pip install --upgrade-pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Docker build
        run: |
          docker build -t ${{ secrets.ARTIFACTORY_URL }}/financial-app:${{ github_sha }}
          
       




        

  
